---
- hosts: jenkins-servers
  remote_user: ec2-user
  sudo: yes
  tasks: 
  - name: Install Java package
    yum: pkg=java state=latest
- hosts: jenkins-servers
  remote_user: ec2-user
  vars: 
    jenkins_repo_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo 
    jenkins_repo_file: /etc/yum.repos.d/jenkins.repo 
    jenkins_key_url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  sudo: yes
  tasks:
  - name: Retreive Jenkins repo information 
    get_url: "dest={{ jenkins_repo_file }} url={{ jenkins_repo_url }}" 
  - name: Add the Jenkins repository to the yum repos
    rpm_key: "state=present key={{ jenkins_key_url }}" 
  - name: Install Jenkins (ensure service starts on boot)
    yum: pkg=jenkins state=latest
    notify:
    - restart jenkins
  - name: Ensure Jenkins starts on boot
    service: name=jenkins enabled=yes 
  handlers:
    - name: restart jenkins
      service: name=jenkins state=restarted
