---
- hosts: jenkins-servers
  remote_user: ec2-user
  vars: 
    jenkins_repo_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo 
    jenkins_repo_file: /etc/yum.repos.d/jenkins.repo 
    jenkins_key_url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  sudo: yes
  tasks:
  - name: Retreive Jenkins repo information 
    command: "wget -O {{ jenkins_repo_file }} {{ jenkins_repo_url }}" 
  - name: Add the Jenkins repository to the yum repos
    command: "rpm --import {{ jenkins_key_url }}" 
  - name: Install Jenkins
    yum: pkg=jenkins state=latest
