---
- hosts: all
  tasks:
    - name: 'testing with_items'
      shell: 'echo {{ item }}'
      with_items:
        - one
        - two
        - three
    - name: 'failing task'
      shell: 'exit 1'
