---
- hosts: all
  tasks:
    - name: 'testing with_items'
      shell: 'echo {{ item }}'
      with_items:
        - one
        - two
        - three
    - name: 'items with different results'
      shell: 'exit {{ item }}'
      with_items:
        - 0
        - 1
